version: '{branch}-{build}'
skip_non_tags: true
image: Visual Studio 2022

environment:
  matrix:
    - BUILD_NAME: Qt5-x86
      QT_DIR: C:\Qt\5.15.2\msvc2019
      ARCH: x86
      USE_QT6: OFF
      GENERATOR: "NMake Makefiles"
    - BUILD_NAME: Qt6-x64
      QT_DIR: C:\Qt\6.8\msvc2019_64
      ARCH: x64
      USE_QT6: ON
      GENERATOR: "NMake Makefiles"

install:
  - ps: |
      Write-Host "Using Qt version from: $env:QT_DIR"
      $env:PATH += ";$env:QT_DIR\bin"

      # Download latest ImageMagick version
      $gitTags = git ls-remote --sort="version:refname" --tags https://github.com/ImageMagick/ImageMagick.git
      $lastTagLine = $gitTags[-1]
      $lastTagVersion = $lastTagLine -replace '.*refs/tags/(.*)', '$1'
      Write-Host "---`nLatest ImageMagick Version Found: $lastTagVersion`n---"

      Invoke-WebRequest -Uri https://imagemagick.org/archive/binaries/ImageMagick-$lastTagVersion-Q16-HDRI-$env:ARCH-dll.exe -OutFile ImageMagick-Installer.exe
      
      Start-Process -FilePath ".\ImageMagick-Installer.exe" -ArgumentList "/MERGETASKS=install_devel", "/VERYSILENT", "/DIR=C:\projects\ImageMagick" -NoNewWindow -Wait

build_script:
  - cmd: >-
      call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" -arch=%ARCH%

      cd C:\projects\converseen

      mkdir build

      cd build

      cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=Release -DImageMagick_EXECUTABLE_DIR="C:\projects\ImageMagick" -DUSE_QT6=%USE_QT6% ..

      nmake

      cpack -B package

      mkdir artifact

      copy package\*.msi artifact\

      copy package\*.zip artifact\

      7z a -tzip artifact-%BUILD_NAME%.zip artifact\


artifacts:
- path: build/artifact-*.zip
  name: artifact



#deploy:
#- provider: Webhook
#  url: https://app.signpath.io/API/v1/71fbb5b8-055f-4882-ae15-f3a8a2951f83/Integrations/AppVeyor?ProjectSlug=Converseen&SigningPolicySlug=release-signing&ArtifactConfigurationSlug=initial
#  # url: https://app.signpath.io/API/v1/71fbb5b8-055f-4882-ae15-f3a8a2951f83/Integrations/AppVeyor?ProjectSlug=Converseen&SigningPolicySlug=test-signing&ArtifactConfigurationSlug=initial
#  authorization:
#     secure: YoYalnXJBOqOYvwfVK1CtgGyCk5oeNQNyr+8ru9xjnEbydKxGokat+WO47aGhq6vaT0tx0cWUZBTJYwsaVmWbA==
