version: '{branch}-{build}'
skip_non_tags: true
image: Visual Studio 2022
environment:
  Qt5_INSTALL_DIR: C:\Qt\5.15.2\msvc2019
  Qt6_INSTALL_DIR: C:\Qt\6.8.1\msvc2022_64
build_script:
- ps: |
    $env:PATH += ";$env:$QT5_VERSION\bin;$env:$QT6_VERSION\bin"

    # Get latest version number from GitHub
    $gitTags = git ls-remote --sort="version:refname" --tags https://github.com/ImageMagick/ImageMagick.git
    $lastTagLine = $gitTags[-1]
    $lastTagVersion = $lastTagLine -replace '.*refs/tags/(.*)', '$1'
    $latestVersionNumber = $lastTagVersion

    Write-Host "---`nLatest ImageMagick Version Found: $latestVersionNumber`n---"

    # Download ImageMagick 32 bit and 64 bit
    Invoke-WebRequest -Uri https://imagemagick.org/archive/binaries/ImageMagick-$latestVersionNumber-Q16-HDRI-x86-dll.exe -OutFile ImageMagick-Installer-32.exe
    Invoke-WebRequest -Uri https://imagemagick.org/archive/binaries/ImageMagick-$latestVersionNumber-Q16-HDRI-x64-dll.exe -OutFile ImageMagick-Installer-64.exe
    
    Start-Process -FilePath ".\ImageMagick-Installer-32.exe.exe" -ArgumentList "/MERGETASKS=install_devel", "/VERYSILENT", "/DIR=C:\projects\ImageMagick-32" -NoNewWindow -Wait
    Start-Process -FilePath ".\ImageMagick-Installer-64.exe.exe" -ArgumentList "/MERGETASKS=install_devel", "/VERYSILENT", "/DIR=C:\projects\ImageMagick-64" -NoNewWindow -Wait
    
- cmd: >-
    # Build Qt5 32 Bit
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"

    cd C:\projects\converseen

    mkdir build-qt5
    cd build-qt5

    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE:STRING=Release -DImageMagick_EXECUTABLE_DIR="C:\projects\ImageMagick-32" ..
    nmake
    cpack -G ZIP -B package

- cmd: >-
    # Build Qt6 64 Bit
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"

    cd C:\projects\converseen

    mkdir build-qt6
    cd build-qt6

    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE:STRING=Release -DImageMagick_EXECUTABLE_DIR="C:\projects\ImageMagick-64" -DUSE_QT6=yes ..
    nmake
    cpack -B package

- cmd: >-
    # Create Artifact
    cd C:\projects\converseen
    mkdir -p artifact/qt5
    mkdir -p artifact/qt6

    cp build-qt5/package/*.zip artifact/qt5.
    cp build-qt6/package/*.msi artifact/qt6.
    cp build-qt6/package/*.zip artifact/qt6.
    
    7z a -tzip artifact.zip artifact/

artifacts:
- path: artifact.zip
  name: artifact

#deploy:
#- provider: Webhook
#  url: https://app.signpath.io/API/v1/71fbb5b8-055f-4882-ae15-f3a8a2951f83/Integrations/AppVeyor?ProjectSlug=Converseen&SigningPolicySlug=release-signing&ArtifactConfigurationSlug=initial
#  # url: https://app.signpath.io/API/v1/71fbb5b8-055f-4882-ae15-f3a8a2951f83/Integrations/AppVeyor?ProjectSlug=Converseen&SigningPolicySlug=test-signing&ArtifactConfigurationSlug=initial
#  authorization:
#     secure: YoYalnXJBOqOYvwfVK1CtgGyCk5oeNQNyr+8ru9xjnEbydKxGokat+WO47aGhq6vaT0tx0cWUZBTJYwsaVmWbA==
