name: converseen
version: '0.15.1.1'
summary: Converseen - A Batch Image Converter, Resizer and Processor for your Pictures!
description: |
  Converseen is a free and cross-platform batch image processor that allows you to convert, resize, rotate, and flip an infinite number of images with a mouse click. Converseen is also able to transform an entire PDF file into a group of images with the characteristics you prefer: you can choose one of the 100+ formats, set the size, resolution, and the filename.
  Converseen, thanks to ImageMagick, supports more than 100 image formats including JPEG, GIF, PNG, TIFF, WEBP, and many others.

  Project's Website: https://converseen.fasterland.net/
  GitHub Page: https://github.com/Faster3ck/Converseen

grade: stable
confinement: strict
base: core24
icon: res/converseen.png
license: GPL-3.0
compression: lzo

apps:
  converseen:
    common-id: net.fasterland.converseen
    command: usr/bin/converseen
    environment:
      # Set heif plugins path
      LIBHEIF_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/libheif/plugins
      # Set Ghostscript env
      GS_VERSION: "10.02.1"
      GS_LIB: $SNAP/usr/share/ghostscript/${GS_VERSION}/Resource/Init
      GS_FONTPATH: $SNAP/usr/share/ghostscript/${GS_VERSION}/Resource/Font
      GS_OPTIONS: "-sGenericResourceDir=$SNAP/usr/share/ghostscript/${GS_VERSION}/Resource/ -sICCProfilesDir=$SNAP/usr/share/ghostscript/${GS_VERSION}/iccprofiles/"
    extensions:
      - kde-neon-6
    desktop: usr/share/applications/net.fasterland.converseen.desktop
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - pulseaudio
      - desktop
      - desktop-legacy
      - wayland
      - unity7

# Converseen Main Program
parts:
  converseen:
    plugin: cmake
    source: https://github.com/Faster3ck/Converseen.git
    source-type: git
    source-branch: main
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
      - -DCMAKE_INSTALL_SYSCONFDIR=/etc
      - -DCMAKE_INSTALL_LOCALSTATEDIR=/var
      - -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON
      - -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF
      - -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON
      - -DCMAKE_INSTALL_RUNSTATEDIR=/run
      - -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON
      - -DCMAKE_VERBOSE_MAKEFILE=ON
      - -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - --log-level=STATUS
      - -DCMAKE_LIBRARY_PATH=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -DUSE_QT6=yes
    build-environment: &build-environment
      - LD_LIBRARY_PATH: >
         "/snap/mesa-2404/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$LD_LIBRARY_PATH"
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
    after:
      - imagemagick7

  imagemagick7:
    plugin: autotools
    source: https://imagemagick.org/download/ImageMagick.tar.gz
    autotools-configure-parameters:
      - "--enable-shared"
      - "--disable-installed"
      - "--enable-hdri"
      - "--without-perl"
      - "--disable-dependency-tracking"
      - "--with-gslib=yes"
      - "--with-openjp2"
      - "--with-wmf"
      - "--without-gvc"
      - "--with-djvu"
      - "--without-dps"
      - "--without-fpx"
      - "--with-heic=yes"
      - "--with-jxl=yes"
      - "--with-fftw=no"
      - "--with-freetype=yes"
      - "--prefix=/usr"
    build-packages:
      - libffi-dev
      - zlib1g-dev
      - liblcms2-dev
      - libtiff-dev
      - libopenjp2-7-dev
      - libwebp-dev
      - libde265-dev
      - libheif-dev
      - libgif-dev
      - libfontconfig1-dev
      - libdjvulibre-dev
      - libgs-dev
      - libwmf-dev
      - libxml2-dev
      - liblqr-1-0-dev
      - libraw-dev
      - libimath-dev
      - libopenexr-dev
      - libdeflate-dev
      - libraqm-dev
      - libjxl-dev
      - libx265-dev
    stage-packages:
      - libffi8
      - zlib1g
      - liblcms2-2
      - libtiff6
      - libopenjp2-7
      - libwebp7
      - libde265-0
      - libheif1
      - libgif7
      - libfontconfig1
      - libdjvulibre21
      - libgs10
      - libwmf0.2-7
      - libxml2
      - liblqr-1-0
      - libraw23
      - libopenexr-3-1-30
      - libdeflate0
      - libraqm0
      - libx265-199
      - libheif-plugin-aomdec
      - libheif-plugin-aomenc
      - libheif-plugin-dav1d
      - libheif-plugin-libde265
      - libheif-plugin-x265
      - libjxl0.7
      - libicu74
      - libicu-dev

  cleanup:
    after:
      - imagemagick7
      - converseen
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24

    override-prime: |
      set -eux

      for snap in "core24" "kf6-core24"; do
        cd "/snap/$snap/current"
        find . \( -type f -o -type l ! -xtype d \) -print \
            | sed 's|^./|/root/prime/|' \
            | xargs -r rm -f
      done

      # Remove ImageMagick-7 unnecessary files:
      rm -f $SNAPCRAFT_PRIME/usr/bin/animate
      rm -f $SNAPCRAFT_PRIME/usr/bin/conjure
      rm -f $SNAPCRAFT_PRIME/usr/bin/display
      rm -f $SNAPCRAFT_PRIME/usr/bin/magick
      rm -f $SNAPCRAFT_PRIME/usr/bin/magick-script
      rm -f $SNAPCRAFT_PRIME/usr/bin/montage
      rm -f $SNAPCRAFT_PRIME/usr/bin/compare
      rm -f $SNAPCRAFT_PRIME/usr/bin/identify
      rm -f $SNAPCRAFT_PRIME/usr/bin/Magick++-config
      rm -f $SNAPCRAFT_PRIME/usr/bin/MagickWand-config
      rm -f $SNAPCRAFT_PRIME/usr/bin/MagickWand
      rm -f $SNAPCRAFT_PRIME/usr/bin/config
      rm -f $SNAPCRAFT_PRIME/usr/bin/stream
      rm -f $SNAPCRAFT_PRIME/usr/bin/composite
      rm -f $SNAPCRAFT_PRIME/usr/bin/convert
      rm -f $SNAPCRAFT_PRIME/usr/bin/import
      rm -f $SNAPCRAFT_PRIME/usr/bin/MagickCore-config
      rm -f $SNAPCRAFT_PRIME/usr/bin/mogrify
      rm -rf $SNAPCRAFT_PRIME/usr/include
      rm -f $SNAPCRAFT_PRIME/usr/lib/*.a
      rm -rf $SNAPCRAFT_PRIME/usr/share/doc/ImageMagick-7/images
      rm -rf $SNAPCRAFT_PRIME/usr/share/doc/ImageMagick-7/www
      rm -rf $SNAPCRAFT_PRIME/usr/share/doc/ImageMagick-7/index.html
