name: Build and Release Snap Package

on:
  push:
    tags:        
      - '**'
  workflow_dispatch:
      
permissions:
  contents: write

jobs:
  sourceforge-prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft
        with:
          path: package/Snap

      - name: Plublish Snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: stable
