name: Build and Release Snap Package

on:
  push:
    tags:        
      - '**'
  workflow_dispatch:
      
permissions:
  contents: write

env:
  QT_QPA_PLATFORM: offscreen

jobs:
  snap-build-release:
    name: Converseen Snap Build (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - arch: amd64
            os: ubuntu-latest
          - arch: arm64
            os: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v6
      
      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft
        with:
          path: package/Snap
    
      - name: Snap Test Run
        run: |
          sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
          converseen -p

      - name: Publish Snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: stable
